# Generated by Django 3.1.6 on 2021-02-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_data_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='user',
        ),
        migrations.AddField(
            model_name='data',
            name='userId',
            field=models.IntegerField(default=0),
        ),
    ]
